CREATE OR REPLACE FUNCTION BUSCAPRODUTO(NOME_PRODUTO VARCHAR(50)) RETURNS INTEGER AS $$
	DECLARE
		PROD_ID INTEGER;
	BEGIN
		SELECT PRODUTO_ID INTO PROD_ID FROM PRODUTO WHERE NOME LIKE NOME_PRODUTO;
		RETURN PROD_ID;
	END
	$$ LANGUAGE plpgsql;

DROP FUNCTION BUSCALOCAL;

CREATE OR REPLACE FUNCTION procura_local_por_nome(nome_local VARCHAR(50)) RETURNS integer AS $$
	DECLARE
		ID INTEGER;
	BEGIN
		SELECT LOCAL_ID INTO ID FROM LOCAL WHERE BAIRRO LIKE NOME_LOCAL;
		RETURN ID;
	END;
	$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION BUSCALOCAL(L_ID INTEGER) RETURNS VARCHAR(50) AS $$
	DECLARE
		LOCAL_NOME VARCHAR(50);
	BEGIN
		SELECT LOCAL.BAIRRO INTO LOCAL_NOME FROM LOCAL WHERE LOCAL_ID = L_ID;
		RETURN LOCAL_NOME;
	END
	$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION VERIFICALOCAL(L_ID INTEGER) RETURNS INTEGER AS $$
	DECLARE
		LOCAL_NOME VARCHAR(50);
		SEARCH_RESULT INTEGER;
	BEGIN
		LOCAL_NOME := BUSCALOCAL(L_ID);
		SELECT LOJA_ID INTO SEARCH_RESULT FROM LOJA WHERE ENDERECO LIKE LOCAL_NOME;

		IF SEARCH_RESULT IS NULL THEN
			RETURN 1;
		ELSE
			RETURN L_ID;
		END IF;
	END
	
	$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION CADASTRACLIENTE(CPF VARCHAR(11), NOME VARCHAR(50), EMAIL VARCHAR(30), TELEFONE VARCHAR(11), DT_NASC DATE) RETURNS VOID AS $$
	DECLARE
		ID INTEGER;
	BEGIN 
		SELECT MAX(CLIENTE_ID) INTO ID FROM CLIENTE;
		INSERT INTO CLIENTE VALUES(ID + 1, CPF, NOME, EMAIL, TELEFONE, DT_NASC, TRUE);
	END;
	$$ LANGUAGE 'plpgsql';
		
		


CREATE OR REPLACE FUNCTION REALIZAVENDA(NOME_PROD VARCHAR(50), CPF VARCHAR(11), NOME_LOCAL VARCHAR(50)) RETURNS TEXT AS $$
	DECLARE
		PROD_ID INTEGER;
		CLIENTE_ID INTEGER;
		LOCAL_ID INTEGER;

	BEGIN
		
